[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "credit-risk-model"
version = "0.1.0"

[tool.setuptools]
packages = ["src"]
package-dir = {"" = "src"}